name: Build Protobuf stubs

on: [push]

jobs:
  javascript:
    runs-on: ubuntu-latest
    name: Build Javascript stubs

    steps:
      - uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build JS Stubs
        run: |
          npm i
          node ./js/bin/build_stubs.js

      - name: Commit to repository
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@users.noreply.github.com"
          git add js/*
          git diff --quiet && git diff --staged --quiet || (git commit -m "Build Javascript stubs"; git push)

  swift:
    runs-on: macos-latest
    name: Build Swift stubs
  
    steps:
      - uses: actions/checkout@v2

      - name: Set up Swift 
        run: brew install swift-protobuf

      - name: Build swift stubs
        run: |
          mkdir -p swift
          protoc -I=protobuf --swift_opt=Visibility=Public --swift_out=swift $(find protobuf -name "*.proto")
          
      - name: Commit to repository 
        run: |
            git config user.name "GitHub Action"
            git config user.email "actions@users.noreply.github.com"
            git add swift/*
            git diff --quiet && git diff --staged --quiet || (git commit -m "Build Swift stubs"; git push)

